### PR TITLE
Period converted projection

### PR DESCRIPTION
**Pull request by lixiliu**
Change test data to accept period interval type-converted and time-wrapped behaviors in dsgrid.

dsgrid companion PR: https://github.com/dsgrid/dsgrid/pull/228

### CODE REVIEW

**Comment by daniel-thom** [comment]
The files you changed are generated by running `dsgrid-admin make-filtered-registry` on the StandardScenarios project. Are your changes one-off changes or are you also going to make changes to the SS repo?

**Review by elainethale — COMMENTED** [review]
Please excuse my ignorance, but do we want ._SUCCESS.crc and .snappy.parquet.crc files in this repository, or just .parquet files?

**Comment by daniel-thom** [comment]
> Please excuse my ignorance, but do we want ._SUCCESS.crc and .snappy.parquet.crc files in this repository, or just .parquet files?

Those are required. Spark checks the CRCs when loading the Parquets in order to verify the contents.

**Comment by daniel-thom** [comment]
@elainethale @lixiliu My take is this: don't make this change. I don't know how many tests will fail without it. We can either mark those to be skipped or tolerate the failures. Once all of the dsgrid PRs are merged (hopefully today or tomorrow) I will regenerate all of the datasets and then re-create this filtered registry.

**Comment by lixiliu** [comment]
Old branch, no longer relevant

**Pull request closed without merging**
